apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberay-operator
spec:
  template:
    spec:
      priorityClassName: system-node-critical
      containers:
      - name: kuberay-operator
        image: $(image)
